### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by simon-p-r**
Saw this issue on SO and thought I would make it clearer how op should use hapi and test with server.inject if code was cleaner.  Also async errrors should not be thrown, instead they should be returned to client via Boom module.

### CODE REVIEW

**Comment by davethomas11** [comment]
Hi Simon,

This is awesome thank you! Considering I am very new to hapi, I really like seeing and learning how it should be properly used. I will bring in the pull request here. I am having trouble finding the command line, command to run the server after your changes? If I just wanted to launch the server with out tests what would that be? I'd like to check it out before I merge.

**Comment by simon-p-r** [comment]
just `npm t` to run test script

**Comment by simon-p-r** [comment]
And to run server `node lib/index.js`

**Comment by davethomas11** [comment]
Node lib/index.hs returns to command line with no output for me:

```
[dave@David-Thomass-MacBook-Pro so39432656]$ git branch
  master
* simon-p-r-fix
[dave@David-Thomass-MacBook-Pro so39432656]$ node lib/index.js
[dave@David-Thomass-MacBook-Pro so39432656]$
```

**Comment by davethomas11** [comment]
I'll be a little slow replying again. On my way to work!

**Comment by simon-p-r** [comment]
I will add an npm start script for starting server directly.

**Comment by simon-p-r** [comment]
I have added a start command so if you type `npm start` server will start

**Comment by davethomas11** [comment]
Very nice. Thank you for the great merge. Hopefully we can help this fellow, Grouchy, find the cause of his "grouchiness". 🍺

**Comment by simon-p-r** [comment]
No worries hope it explains things cleanly enough 👍 for user

**Pull request merged**
